### PR TITLE
Split dependancies

### PR DESCRIPTION
**Pull request by Fantomas42**
Split dependencies in setup script + PEP8

By default only the libraries necessary for running the rpc interface are installed.

We can install the cli and the web components via extra_requires.

### CODE REVIEW

**Comment by Fantomas42** [comment]
I don't have made some extensive tests, so a review is needed.

**Comment by guy881** [comment]
Nice, would love to see this merged. Although I think it would be good to provide some instruction for installation in README. :)

**Comment by tiagocoutinho** [comment]
> would be good to provide some instruction for installation in README.
Agree. The README should be modified to reflect these changes

**Comment by guy881** [comment]
@Fantomas42  it would be really great to get this merged. Are you still willing to work on that? Adding a proper section in README would be helpful.

**Comment by tiagocoutinho** [comment]
Changes applied as part of the #68

**Pull request closed without merging**
