### PR TITLE
Login capabilities

### PR DESCRIPTION
**Pull request by guy881**
Server:
* flask session authentication, user is required to store secret key (as environmental variable called `MULTIVISOR_SECRET_KEY`),
* `/api/login`, `/api/logout` and `/api/auth` endpoints,
* username and password stored in multivisor configuration file,
* `login_required` decorator for restricting the access to the view,
* constant time password comparison,

Frontend:
* Login page
* Add menu with logout button
* Show menu and toolbar links only if user is authenticated
* Redirect to login page if user is not authenticated
* Redirect to homepage if user is already authenticated and goes to login page

I believe the target should be a future release branch but I can only choose master. Let me know if I should squash commits or something.

Issue: https://github.com/tiagocoutinho/multivisor/issues/8

### CODE REVIEW

**Comment by tiagocoutinho** [comment]
@guy881,
LGTM.

I have created a develop branch. Could you change this PR target branch to *develop*?
Thanks a lot for your contribution.

**Comment by guy881** [comment]
Ok, @tiagocoutinho, done!

**Comment by tiagocoutinho** [comment]
@guy881, there seen be conflicts so I cannot merge. Could you have a look? thanks

**Comment by guy881** [comment]
@tiagocoutinho are you sure about this? Maybe I am doing something wrong, but github shows no conflicts.
image

**Comment by tiagocoutinho** [comment]
Strange... I have this:
image

**Comment by tiagocoutinho** [comment]
Ok, doing it by hand...

**Pull request merged**
